### ISSUE TITLE
Looping scroller, no scrollbar 

### ISSUE THREAD

**Issue by joeleby** [getsetbro/padmachine#5]
If possible... the list of keys should scroll endlessly. On the far right, it should start again so that the user never gets to the beginning or end of the list of keys. 

Related: there's currently a standard scrollbar that is displaying. Can it be hidden? If the scrollable content is endless it should not be indicating a position.

**Comment by getsetbro** [comment]
For now I will add C on the end in case you want to start in B and go up.

**Comment by getsetbro** [comment]
What if instead you had a button to take it up a key?

**Comment by joeleby** [comment]
Let's not do this item for now - I want to think about a better way to display the keys. Something that looks more like a keyboard would be good.
